% P1B - regras aprendidas pelo RapidMiner (Altair AI Studio)
% CF = confianca empirica (proporcao da classe maioritaria na folha).
% DEBUG primeiraCond = apoio_domicilio > 0.500
% DEBUG primeiroVal  = 0.500
% DEBUG distribuicao de #filhos por no interno: [2:80]
% DEBUG total de regras = 80

:- op( 800, fx, if).
:- op( 700, xfx, then).
:- op( 600, xfx, with).
:- op( 300, xfy, or).
:- op( 200, xfy, and).
:- multifile( (if)/1 ).

if apoio_domicilio and nao_melhora_antipiretico and confusao and agravamento and dor_cabeca_forte and febre_persistente and dor_abdominal and nausea and convulsoes and dor_garganta and congestao_nasal and dor_cabeca and falta_ar and convulsao_febril and manchas_pele and imunodeprimido and tratamento_oncologico and gravidez and doenca_cronica and idade_risco then transferir_triagem with 0.9.
if apoio_domicilio and nao_melhora_antipiretico and confusao and agravamento and dor_cabeca_forte and febre_persistente and dor_abdominal and nausea and convulsoes and dor_garganta and congestao_nasal and dor_cabeca and falta_ar and convulsao_febril and manchas_pele and imunodeprimido and tratamento_oncologico and gravidez and doenca_cronica then adr_su with 0.9.
if apoio_domicilio and nao_melhora_antipiretico and confusao and agravamento and dor_cabeca_forte and febre_persistente and dor_abdominal and nausea and convulsoes and dor_garganta and congestao_nasal and dor_cabeca and falta_ar and convulsao_febril and manchas_pele and imunodeprimido and tratamento_oncologico and gravidez then adr_su with 0.9.
if apoio_domicilio and nao_melhora_antipiretico and confusao and agravamento and dor_cabeca_forte and febre_persistente and dor_abdominal and nausea and convulsoes and dor_garganta and congestao_nasal and dor_cabeca and falta_ar and convulsao_febril and manchas_pele and imunodeprimido and tratamento_oncologico then adr_su with 0.9.
if apoio_domicilio and nao_melhora_antipiretico and confusao and agravamento and dor_cabeca_forte and febre_persistente and dor_abdominal and nausea and convulsoes and dor_garganta and congestao_nasal and dor_cabeca and falta_ar and convulsao_febril and manchas_pele and imunodeprimido then adr_su with 0.9.
if apoio_domicilio and nao_melhora_antipiretico and confusao and agravamento and dor_cabeca_forte and febre_persistente and dor_abdominal and nausea and convulsoes and dor_garganta and congestao_nasal and dor_cabeca and falta_ar and convulsao_febril and manchas_pele then adr_su with 0.9.
if apoio_domicilio and nao_melhora_antipiretico and confusao and agravamento and dor_cabeca_forte and febre_persistente and dor_abdominal and nausea and convulsoes and dor_garganta and congestao_nasal and dor_cabeca and falta_ar and convulsao_febril then adr_su with 0.9.
if apoio_domicilio and nao_melhora_antipiretico and confusao and agravamento and dor_cabeca_forte and febre_persistente and dor_abdominal and nausea and convulsoes and dor_garganta and congestao_nasal and dor_cabeca and falta_ar then adr_su with 0.9.
if apoio_domicilio and nao_melhora_antipiretico and confusao and agravamento and dor_cabeca_forte and febre_persistente and dor_abdominal and nausea and convulsoes and dor_garganta and congestao_nasal and dor_cabeca then adr_su with 0.9.
if apoio_domicilio and nao_melhora_antipiretico and confusao and agravamento and dor_cabeca_forte and febre_persistente and dor_abdominal and nausea and convulsoes and dor_garganta and congestao_nasal and fadiga_mialgias and falta_ar and convulsao_febril and manchas_pele and imunodeprimido and tratamento_oncologico and gravidez and doenca_cronica and idade_risco then transferir_triagem with 0.9.
if apoio_domicilio and nao_melhora_antipiretico and confusao and agravamento and dor_cabeca_forte and febre_persistente and dor_abdominal and nausea and convulsoes and dor_garganta and congestao_nasal and fadiga_mialgias and falta_ar and convulsao_febril and manchas_pele and imunodeprimido and tratamento_oncologico and gravidez and doenca_cronica then adr_su with 0.9.
if apoio_domicilio and nao_melhora_antipiretico and confusao and agravamento and dor_cabeca_forte and febre_persistente and dor_abdominal and nausea and convulsoes and dor_garganta and congestao_nasal and fadiga_mialgias and falta_ar and convulsao_febril and manchas_pele and imunodeprimido and tratamento_oncologico and gravidez then adr_su with 0.9.
if apoio_domicilio and nao_melhora_antipiretico and confusao and agravamento and dor_cabeca_forte and febre_persistente and dor_abdominal and nausea and convulsoes and dor_garganta and congestao_nasal and fadiga_mialgias and falta_ar and convulsao_febril and manchas_pele and imunodeprimido and tratamento_oncologico then adr_su with 0.9.
if apoio_domicilio and nao_melhora_antipiretico and confusao and agravamento and dor_cabeca_forte and febre_persistente and dor_abdominal and nausea and convulsoes and dor_garganta and congestao_nasal and fadiga_mialgias and falta_ar and convulsao_febril and manchas_pele and imunodeprimido then adr_su with 0.9.
if apoio_domicilio and nao_melhora_antipiretico and confusao and agravamento and dor_cabeca_forte and febre_persistente and dor_abdominal and nausea and convulsoes and dor_garganta and congestao_nasal and fadiga_mialgias and falta_ar and convulsao_febril and manchas_pele then adr_su with 0.9.
if apoio_domicilio and nao_melhora_antipiretico and confusao and agravamento and dor_cabeca_forte and febre_persistente and dor_abdominal and nausea and convulsoes and dor_garganta and congestao_nasal and fadiga_mialgias and falta_ar and convulsao_febril then adr_su with 0.9.
if apoio_domicilio and nao_melhora_antipiretico and confusao and agravamento and dor_cabeca_forte and febre_persistente and dor_abdominal and nausea and convulsoes and dor_garganta and congestao_nasal and fadiga_mialgias and falta_ar then adr_su with 0.9.
if apoio_domicilio and nao_melhora_antipiretico and confusao and agravamento and dor_cabeca_forte and febre_persistente and dor_abdominal and nausea and convulsoes and dor_garganta and congestao_nasal and fadiga_mialgias then adr_su with 0.9.
if apoio_domicilio and nao_melhora_antipiretico and confusao and agravamento and dor_cabeca_forte and febre_persistente and dor_abdominal and nausea and convulsoes and dor_garganta and congestao_nasal then transferir_triagem with 0.9.
if apoio_domicilio and nao_melhora_antipiretico and confusao and agravamento and dor_cabeca_forte and febre_persistente and dor_abdominal and nausea and convulsoes and dor_garganta then transferir_triagem with 0.9.
if apoio_domicilio and nao_melhora_antipiretico and confusao and agravamento and dor_cabeca_forte and febre_persistente and dor_abdominal and nausea and convulsoes then transferir_triagem with 0.9.
if apoio_domicilio and nao_melhora_antipiretico and confusao and agravamento and dor_cabeca_forte and febre_persistente and dor_abdominal and nausea and febre_alta_40 and falta_ar_leve and disuria and falta_ar and compromisso_via_aerea and desidratacao and convulsao_febril and manchas_pele and vomitos then transferir_triagem with 0.87.
if apoio_domicilio and nao_melhora_antipiretico and confusao and agravamento and dor_cabeca_forte and febre_persistente and dor_abdominal and nausea and febre_alta_40 and falta_ar_leve and disuria and falta_ar and compromisso_via_aerea and desidratacao and convulsao_febril and manchas_pele then adr_su with 0.9.
if apoio_domicilio and nao_melhora_antipiretico and confusao and agravamento and dor_cabeca_forte and febre_persistente and dor_abdominal and nausea and febre_alta_40 and falta_ar_leve and disuria and falta_ar and compromisso_via_aerea and desidratacao and convulsao_febril then adr_su with 0.9.
if apoio_domicilio and nao_melhora_antipiretico and confusao and agravamento and dor_cabeca_forte and febre_persistente and dor_abdominal and nausea and febre_alta_40 and falta_ar_leve and disuria and falta_ar and compromisso_via_aerea and desidratacao then adr_su with 0.9.
if apoio_domicilio and nao_melhora_antipiretico and confusao and agravamento and dor_cabeca_forte and febre_persistente and dor_abdominal and nausea and febre_alta_40 and falta_ar_leve and disuria and falta_ar and compromisso_via_aerea then adr_su with 0.9.
if apoio_domicilio and nao_melhora_antipiretico and confusao and agravamento and dor_cabeca_forte and febre_persistente and dor_abdominal and nausea and febre_alta_40 and falta_ar_leve and disuria and falta_ar then inem with 0.9.
if apoio_domicilio and nao_melhora_antipiretico and confusao and agravamento and dor_cabeca_forte and febre_persistente and dor_abdominal and nausea and febre_alta_40 and falta_ar_leve and disuria and pieira_ou_tiragem and dor_toracica then adr_su with 0.9.
if apoio_domicilio and nao_melhora_antipiretico and confusao and agravamento and dor_cabeca_forte and febre_persistente and dor_abdominal and nausea and febre_alta_40 and falta_ar_leve and disuria and pieira_ou_tiragem then inem with 0.9.
if apoio_domicilio and nao_melhora_antipiretico and confusao and agravamento and dor_cabeca_forte and febre_persistente and dor_abdominal and nausea and febre_alta_40 and falta_ar_leve and disuria then inem with 0.9.
if apoio_domicilio and nao_melhora_antipiretico and confusao and agravamento and dor_cabeca_forte and febre_persistente and dor_abdominal and nausea and febre_alta_40 and falta_ar_leve then transferir_triagem with 0.9.
if apoio_domicilio and nao_melhora_antipiretico and confusao and agravamento and dor_cabeca_forte and febre_persistente and dor_abdominal and nausea and febre_alta_40 then transferir_triagem with 0.9.
if apoio_domicilio and nao_melhora_antipiretico and confusao and agravamento and dor_cabeca_forte and febre_persistente and dor_abdominal and nausea then inem with 0.9.
if apoio_domicilio and nao_melhora_antipiretico and confusao and agravamento and dor_cabeca_forte and febre_persistente and dor_abdominal then inem with 0.9.
if apoio_domicilio and nao_melhora_antipiretico and confusao and agravamento and dor_cabeca_forte and febre_persistente and dor_abdominal_forte then transferir_triagem with 0.9.
if apoio_domicilio and nao_melhora_antipiretico and confusao and agravamento and dor_cabeca_forte and febre_persistente then adr_su with 0.9.
if apoio_domicilio and nao_melhora_antipiretico and confusao and agravamento and dor_cabeca_forte then transferir_triagem with 0.9.
if apoio_domicilio and nao_melhora_antipiretico and confusao and agravamento and febre and disuria and agravamento_48h and fraqueza_lado_corpo and dor_toracica and sangramento_abundante and vomitos_intensos and dor_abdominal_forte and tosse_com_sangue and pieira_ou_tiragem and convulsoes and compromisso_via_aerea and diarreia_grave and trauma_recente and dor_cabeca and nausea and fadiga_mialgias then transferir_triagem with 0.9.
if apoio_domicilio and nao_melhora_antipiretico and confusao and agravamento and febre and disuria and agravamento_48h and fraqueza_lado_corpo and dor_toracica and sangramento_abundante and vomitos_intensos and dor_abdominal_forte and tosse_com_sangue and pieira_ou_tiragem and convulsoes and compromisso_via_aerea and diarreia_grave and trauma_recente and dor_cabeca and nausea then autocuidado with 0.9.
if apoio_domicilio and nao_melhora_antipiretico and confusao and agravamento and febre and disuria and agravamento_48h and fraqueza_lado_corpo and dor_toracica and sangramento_abundante and vomitos_intensos and dor_abdominal_forte and tosse_com_sangue and pieira_ou_tiragem and convulsoes and compromisso_via_aerea and diarreia_grave and trauma_recente and dor_cabeca then autocuidado with 0.9.
if apoio_domicilio and nao_melhora_antipiretico and confusao and agravamento and febre and disuria and agravamento_48h and fraqueza_lado_corpo and dor_toracica and sangramento_abundante and vomitos_intensos and dor_abdominal_forte and tosse_com_sangue and pieira_ou_tiragem and convulsoes and compromisso_via_aerea and diarreia_grave and trauma_recente and espirros then transferir_triagem with 0.9.
if apoio_domicilio and nao_melhora_antipiretico and confusao and agravamento and febre and disuria and agravamento_48h and fraqueza_lado_corpo and dor_toracica and sangramento_abundante and vomitos_intensos and dor_abdominal_forte and tosse_com_sangue and pieira_ou_tiragem and convulsoes and compromisso_via_aerea and diarreia_grave and trauma_recente then autocuidado with 0.9.
if apoio_domicilio and nao_melhora_antipiretico and confusao and agravamento and febre and disuria and agravamento_48h and fraqueza_lado_corpo and dor_toracica and sangramento_abundante and vomitos_intensos and dor_abdominal_forte and tosse_com_sangue and pieira_ou_tiragem and convulsoes and compromisso_via_aerea and diarreia_grave then adr_su with 0.9.
if apoio_domicilio and nao_melhora_antipiretico and confusao and agravamento and febre and disuria and agravamento_48h and fraqueza_lado_corpo and dor_toracica and sangramento_abundante and vomitos_intensos and dor_abdominal_forte and tosse_com_sangue and pieira_ou_tiragem and convulsoes and compromisso_via_aerea then adr_su with 0.9.
if apoio_domicilio and nao_melhora_antipiretico and confusao and agravamento and febre and disuria and agravamento_48h and fraqueza_lado_corpo and dor_toracica and sangramento_abundante and vomitos_intensos and dor_abdominal_forte and tosse_com_sangue and pieira_ou_tiragem and convulsoes then inem with 0.9.
if apoio_domicilio and nao_melhora_antipiretico and confusao and agravamento and febre and disuria and agravamento_48h and fraqueza_lado_corpo and dor_toracica and sangramento_abundante and vomitos_intensos and dor_abdominal_forte and tosse_com_sangue and pieira_ou_tiragem then inem with 0.9.
if apoio_domicilio and nao_melhora_antipiretico and confusao and agravamento and febre and disuria and agravamento_48h and fraqueza_lado_corpo and dor_toracica and sangramento_abundante and vomitos_intensos and dor_abdominal_forte and tosse_com_sangue then inem with 0.9.
if apoio_domicilio and nao_melhora_antipiretico and confusao and agravamento and febre and disuria and agravamento_48h and fraqueza_lado_corpo and dor_toracica and sangramento_abundante and vomitos_intensos and dor_abdominal_forte then inem with 0.9.
if apoio_domicilio and nao_melhora_antipiretico and confusao and agravamento and febre and disuria and agravamento_48h and fraqueza_lado_corpo and dor_toracica and sangramento_abundante and vomitos_intensos then adr_su with 0.9.
if apoio_domicilio and nao_melhora_antipiretico and confusao and agravamento and febre and disuria and agravamento_48h and fraqueza_lado_corpo and dor_toracica and sangramento_abundante then adr_su with 0.9.
if apoio_domicilio and nao_melhora_antipiretico and confusao and agravamento and febre and disuria and agravamento_48h and fraqueza_lado_corpo and dor_toracica then inem with 0.9.
if apoio_domicilio and nao_melhora_antipiretico and confusao and agravamento and febre and disuria and agravamento_48h and fraqueza_lado_corpo then inem with 0.9.
if apoio_domicilio and nao_melhora_antipiretico and confusao and agravamento and febre and disuria and agravamento_48h then inem with 0.9.
if apoio_domicilio and nao_melhora_antipiretico and confusao and agravamento and febre and disuria then adr_su with 0.9.
if apoio_domicilio and nao_melhora_antipiretico and confusao and agravamento and febre then transferir_triagem with 0.9.
if apoio_domicilio and nao_melhora_antipiretico and confusao and agravamento and nausea and rigidez_pescoco and sensibilidade_luz and manchas_pele then transferir_triagem with 0.9.
if apoio_domicilio and nao_melhora_antipiretico and confusao and agravamento and nausea and rigidez_pescoco and sensibilidade_luz then inem with 0.9.
if apoio_domicilio and nao_melhora_antipiretico and confusao and agravamento and nausea and rigidez_pescoco then inem with 0.9.
if apoio_domicilio and nao_melhora_antipiretico and confusao and agravamento and nausea then inem with 0.9.
if apoio_domicilio and nao_melhora_antipiretico and confusao and agravamento then inem with 0.9.
if apoio_domicilio and nao_melhora_antipiretico and confusao and disuria and febre_persistente and falta_ar_leve and dor_garganta and congestao_nasal and dor_cabeca and dor_abdominal and falta_ar and convulsao_febril and manchas_pele and imunodeprimido and tratamento_oncologico and gravidez and doenca_cronica and idade_risco then transferir_triagem with 0.9.
if apoio_domicilio and nao_melhora_antipiretico and confusao and disuria and febre_persistente and falta_ar_leve and dor_garganta and congestao_nasal and dor_cabeca and dor_abdominal and falta_ar and convulsao_febril and manchas_pele and imunodeprimido and tratamento_oncologico and gravidez and doenca_cronica then adr_su with 0.9.
if apoio_domicilio and nao_melhora_antipiretico and confusao and disuria and febre_persistente and falta_ar_leve and dor_garganta and congestao_nasal and dor_cabeca and dor_abdominal and falta_ar and convulsao_febril and manchas_pele and imunodeprimido and tratamento_oncologico and gravidez then adr_su with 0.9.
if apoio_domicilio and nao_melhora_antipiretico and confusao and disuria and febre_persistente and falta_ar_leve and dor_garganta and congestao_nasal and dor_cabeca and dor_abdominal and falta_ar and convulsao_febril and manchas_pele and imunodeprimido and tratamento_oncologico then adr_su with 0.9.
if apoio_domicilio and nao_melhora_antipiretico and confusao and disuria and febre_persistente and falta_ar_leve and dor_garganta and congestao_nasal and dor_cabeca and dor_abdominal and falta_ar and convulsao_febril and manchas_pele and imunodeprimido then adr_su with 0.9.
if apoio_domicilio and nao_melhora_antipiretico and confusao and disuria and febre_persistente and falta_ar_leve and dor_garganta and congestao_nasal and dor_cabeca and dor_abdominal and falta_ar and convulsao_febril and manchas_pele then adr_su with 0.9.
if apoio_domicilio and nao_melhora_antipiretico and confusao and disuria and febre_persistente and falta_ar_leve and dor_garganta and congestao_nasal and dor_cabeca and dor_abdominal and falta_ar and convulsao_febril then adr_su with 0.9.
if apoio_domicilio and nao_melhora_antipiretico and confusao and disuria and febre_persistente and falta_ar_leve and dor_garganta and congestao_nasal and dor_cabeca and dor_abdominal and falta_ar then adr_su with 0.9.
if apoio_domicilio and nao_melhora_antipiretico and confusao and disuria and febre_persistente and falta_ar_leve and dor_garganta and congestao_nasal and dor_cabeca and dor_abdominal and febre_alta_40 then adr_su with 0.9.
if apoio_domicilio and nao_melhora_antipiretico and confusao and disuria and febre_persistente and falta_ar_leve and dor_garganta and congestao_nasal and dor_cabeca and dor_abdominal then adr_su with 0.9.
if apoio_domicilio and nao_melhora_antipiretico and confusao and disuria and febre_persistente and falta_ar_leve and dor_garganta and congestao_nasal and dor_cabeca and dor_abdominal_forte then transferir_triagem with 0.9.
if apoio_domicilio and nao_melhora_antipiretico and confusao and disuria and febre_persistente and falta_ar_leve and dor_garganta and congestao_nasal and dor_cabeca then adr_su with 0.9.
if apoio_domicilio and nao_melhora_antipiretico and confusao and disuria and febre_persistente and falta_ar_leve and dor_garganta and congestao_nasal then transferir_triagem with 0.9.
if apoio_domicilio and nao_melhora_antipiretico and confusao and disuria and febre_persistente and falta_ar_leve and dor_garganta then transferir_triagem with 0.9.
if apoio_domicilio and nao_melhora_antipiretico and confusao and disuria and febre_persistente and falta_ar_leve then transferir_triagem with 0.9.
if apoio_domicilio and nao_melhora_antipiretico and confusao and disuria and febre_persistente then transferir_triagem with 0.9.
if apoio_domicilio and nao_melhora_antipiretico and confusao and disuria then transferir_triagem with 0.9.
if apoio_domicilio and nao_melhora_antipiretico and confusao then transferir_triagem with 0.9.
if apoio_domicilio and nao_melhora_antipiretico then inem with 0.9.
if apoio_domicilio then transferir_triagem with 0.9.
